import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Provider from "./provider";
import StreamVideoProvider from "../providers/StreamClientProvider";
import { Toaster } from "@/components/ui/sonner";

import "react-datepicker/dist/react-datepicker.css";
import "@stream-io/video-react-sdk/dist/css/styles.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-dark-1 text-white">
          <Provider>
            <StreamVideoProvider>
              <Toaster />
              {children}
            </StreamVideoProvider>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
